class Products {
  static final List<String> products = [
  'Abre carta de bronce',
  'Aceite de arg n',
  'ACEITE DE COCO 100ML',
  'Aceite de coco Life Choice',
  'ACEITE DE COCO LIFE CHOISE 600ML',
  'Aceite de eucalipto (frasco)',
  'Aceite de M quina Empacadora al Vacio',
  'Aceite de oliva 125ml',
  'Aceite de Oliva ml.',
  'Aceite de palo santo',
  'Aceite de Sacha Inchi 250ml.',
  'Aceite de ungurahua con certificaci¢n org nica KIWA BCS ml.',
  'Aceite de ungurahua ml.',
  'Aceite esencial cipr‚s/naranja ',
  'Aceite esencial clavo de olor',
  'Aceite esencial c£rcuma 50 ml.',
  'Aceite esencial de Albahaca ml.',
  'Aceite esencial de canela prueba ml.',
  'Aceite esencial de c£rcuma con certificaci¢n org nica ml.',
  'Aceite esencial de c£rcuma ml.',
  'Aceite esencial de c£rcuma ml.',
  'Aceite esencial de eucalipto ml.',
  'Aceite esencial de guayaba ml.',
  'Aceite esencial de hierba luisa ml.',
  'Aceite esencial de ishpink (Oleo Essencial de Ishpink Ocotea',
  'Aceite esencial de ishpink con certificaci¢n org nica ml.',
  'Aceite esencial de ishpink ml.',
  'Aceite esencial de jengibre con certificaci¢n org nica',
  'Aceite esencial de jengibre ml.',
  'Aceite esencial de lima ml.',
  'Aceite esencial de lim¢n 10ml.',
  'Aceite esencial de lim¢n ml.',
  'Aceite esencial de mandarina ml.',
  'Aceite esencial de matico ml.',
  'Aceite esencial de naranja 10 ml.',
  'Aceite esencial de naranja ml.',
  'Aceite esencial de palo Santo ml.',
  'Aceite esencial de romero ml.',
  'Aceite esencial de sinchi sacha ml.',
  'Aceite esencial hierba luisa 50 ml.',
  'Aceite esencial hierba luisa con certificaci¢n org nica ml.',
  'Aceite esencial ishpink 50 ml.',
  'Aceite esencial jengibre 50 ml.',
  'Aceite esencial lavanda',
  'Aceite esencial mandarina 10 ml.',
  'Aceite esencial menta',
  'Aceite esencial palo santo',
  'Aceite esencial pino/romero',
  'Aceite para masajes ikiam ishpink 120ml.',
  'Aceite para masajes ikiam ishpink gal¢n',
  'Aceite para masajes ikiam jengibre 120ml.',
  'Aceite para masajes ikiam jengibre gal¢n',
  'Aceite para masajes ikiam mandarina 120ml.',
  'Aceite para masajes ikiam mandarina gal¢n',
  'Aceite para masajes ikiam naranja 120ml.',
  'Aceite para masajes ikiam naranja gal¢n',
  'Aceite Puro Ungurahua Ikiam 120 ml.',
  'Aceite repelente ikiam hierba luisa 120ml.',
  'Aceite repelente ikiam hierba luisa gal¢n',
  'Aceites esencial de lima 10 ml.',
  'Achiote con certificaci¢n org nica KIWA BCS OKO GARANTIE lb.',
  'Achiote convencional lb.',
  'µcido C¡trico gr.',
  'Acondicionador ikiam ungurahua hl 250ml.',
  'Acondicionador ikiam ungurahua hl 270ml.',
  'Acondicionador ikiam ungurahua hl gal¢n',
  'Acondicionador ikiam ungurahua romero 250ml.',
  'Acondicionador ikiam ungurahua romero 270ml.',
  'Acondicionador ikiam ungurahua romero gal¢n',
  'Acondicionador ungurahua HL 30ml.',
  'Acondicionador ungurahua romero l¡quido 60ml.',
  'Aculyn 38 polymer gr.',
  'Adornos met licos',
  'Agua con gas',
  'Agua con gas lim¢n',
  'Agua Desmineralizada ml.',
  'Agua pure water 625ml',
  'Aji deshidratado 25gr.',
  'Aj¡ deshidratado con certificaci¢n org nica KIWA BCS OKO kg.',
  'Aj¡ deshidratado y molido org nico',
  'Aj¡ seco 30g',
  'AJONJOLI CRUDO 500gr.',
  'AJONJOLITO 25gr (NUTRIAL)',
  'AJONJOLITO 75 gr (NUTRIAL)',
  'Alcancia especial',
  'Alcancia extra especial',
  'Alcancia grande',
  'Alcancias chicas tortuga. burro. sapo',
  'Alcancias grandes rinoceronte caballo vaca',
  'Alcancias medianas fragata. delfin. tiburon',
  'Alcohol Cetilico / cetil alcohol gr.',
  'Alcohol Etilico 96§ gr.',
  'ALI¥O AMAZONICO NUKU- KUMA',
  'Almendra gr.',
  'ALMIDON DE ACHIRA 500gr',
  'AMARANTO POP ENDULZADO 100gr. (CAMARI)',
  'AMARANTO POP NATURAL 100gr. (CAMARI)',
  'Amaranto pulverizado 250gr',
  'AMARANTO VITAL',
  'Angel l mpara',
  'Angel platinado',
  'Angeles con vela',
  'Anillos de semillas',
  'Anillos de tagua',
  'Anillos de tagua',
  'Animales chicos envejecido',
  'Animales chicos especial',
  'Animales chicos extra especiales',
  'Animales de madera (b£ho- elefante) 3 paq',
  'Animales palillero',
  'Animalitos de tagua',
  'Animalitos de tagua',
  'Animalitos mini',
  'Apaga velas angeles',
  'Apaga velas figuras indigenas',
  'APANADURA DE QUINUA PARA CARNE',
  'APANADURA DE QUINUA PARA PESCADO',
  'APANADURA DE QUINUA PARA POLLO',
  'Arawir',
  'Arcos chonta',
  'Aretes con guaya',
  'Aretes de balsa',
  'Aretes de coco',
  'Aretes de mullos',
  'Aretes de plumas',
  'Aretes de semilla y alpaca',
  'Aretes de semilla y plata',
  'Aretes de semillas',
  'Aretes de semillas redondos',
  'Aretes de tagua',
  'Aretes de tagua',
  'Aretes de tagua y plata',
  'Aretes kumai',
  'Aretes peque¤os de tagua',
  'Armadillo en balsa',
  'Aroma Cedro-Verbena gr.',
  'AROMA CHIPS (aromatizadores)',
  'Aroma Durazno gr.',
  'Aroma honey nectar gr.',
  'Aroma Manzana gr.',
  'Aroma Manzanilla gr.',
  'Aroma Sand¡a gr.',
  'Aroma Softedy gr.',
  'Aroma Vainilla gr.',
  'Arriendo del local comercial',
  'Artesanias ra¡ces negras',
  'Asamtim',
  'Atomizador de Aceite repelente 24/410 Blanca Zf.',
  'Atomizador de Body splash 24 / 410 Color Oro',
  'Atrapa sue¤os de paja toquilla',
  'Avena en hojuelas 400gr',
  'Az£car com£n ( sacarosa)',
  'Baile de cintas',
  'Bandas de pueblo',
  'Ba¤os de enertizaci¢n',
  'BARRA DE AMARANTO POP ',
  'BARRA DE QUINUA + AMARANTO',
  'BARRA DE QUINUA CUBIERTA DE CHOCOLATE',
  'Barras energ‚ticas',
  'Baston chonta',
  'Bast¢n de chonta',
  'Bastones fieltro gr',
  'BEBIDA DE ALMENDRA SILK 190 ML ',
  'BEBIDA DE ALMENDRA SILK 946 ML ',
  'Binchas de coco-tsapa',
  'Binchas de semillas',
  'Bodoquera de 1 a 2 metros',
  'Body splash ikiam citricos 150ml.',
  'Body splash ikiam curcuma 150ml.',
  'Body splash ikiam ishpink 150ml.',
  'Body splash ikiam jengibre 150ml.',
  'Bolsos',
  'Bolt. Barr/cereal crocante cobertura chocoalte 20gr',
  'Bolt. Barr/cereal crocante cobertura vainilla 20gr',
  'Bolt. Barr/cereal crocante con banana 20gr',
  'Bolt. Barr/cereal crocante con pasas 20gr',
  'Bolt. Barr/cereal crocante sabor chocoalte 20gr',
  'Bolt. Barra coco pasas 35gr',
  'Bolt. Barra granola caf‚ y chocolate  35gr',
  'Bolt. Barra granola uvilla/maracuy  35gr',
  'botella ',
  'B£ho poros',
  'Buhos de cabuya',
  'Cacao achuar convencional lb.',
  'Cacao con certificaci¢n org nica KIWA BCS OKO GARANTIE lb.',
  'Cacao convencional lb.',
  'Cacao deshidratado convencional lb.',
  'Cacao deshidratado org nico kg.',
  'Cacao Manteca gr.',
  'Cacao shuar convencional lb.',
  'Cacao shuar convencional lb.',
  'Caf‚ americano',
  'Caf‚ capuchino',
  'Caf‚ Caribe 100gr',
  'Caf‚ Caribe 255gr',
  'Caf‚ Caribe 450gr',
  'Caf‚ expreso',
  'Caf‚ Kilamupi 100gr',
  'Caf‚ Kilamupi 150gr',
  'Caf‚ Kilamupi 250gr',
  'Caf‚ Kilamupi 450g',
  'Caf‚ Kilamupi en grano',
  'Caf‚ Liofilizado Velez 50G',
  'Caf‚ tostado y molido el bosque 200 gr.',
  'Caf‚ VAM 225gr',
  'Caf‚ VAM 450gr',
  'Caf‚ victoria',
  'Caf‚ Vilcaroma 100gr',
  'Caf‚ vilcaroma 250gr',
  'Caf‚ vilcaroma 453gr',
  'Caf‚ Vilcaroma en grano',
  'Cafeteria (alimentaci¢n)',
  'Caja de Aceite masaje 12 Unidades Con Divisiones Internas ',
  'Caja de Body Splash 12 Unidades Con Divisiones Internas ',
  'Caja de Cart¢n De Gel Analg‚sico',
  'Caja de Cart¢n De Gel Oriente',
  'Caja de Crema Fluida 12 Unidades Con Divisiones Internas',
  'Caja de Crema Nutritiva 12 Unidades Con Divisiones Internas ',
  'Caja de Jarabe De Jengibre De Adulto ',
  'Caja de Jarabe De Jengibre De Ni¤o',
  'Caja de JL300ml. para 12 Unidades Con Divisiones Internas ',
  'Caja de JL500ml. para 12 Unidades Con Divisiones Internas ',
  'CAJA DE METAL NAVIDE¥A',
  'Caja de Shampoo para 12 Unidades Con Divisiones Internas ',
  'Caja de Te Hierba Luisa E Ishpink',
  'Cajas de Man¡ con certificaci¢n org nica KIWA BCS OKO GARANT',
  'Cajas de man¡ convencional',
  'Cajas madera',
  'Cajas papel reciclado',
  'C liz de ishpink con certificaci¢n org nica KIWA lb.',
  'C liz de ishpink convencional lb.',
  'C liz de ishpink corte t‚ org nico. kg.',
  'C liz de ishpink deshidratado kg.',
  'C liz de ishpink deshidratado y molido org nico',
  'C liz de ishpink molido convencional. kg.',
  'C liz de ishpink',
  'Camisetas',
  'Camote ',
  'Campana de repisa',
  'Canasta de semilla',
  'Canasta suku',
  'Canastas de paja grande',
  'Canastas de paja peque¤a',
  'Canela 10 gr.',
  'Canela Amazon¡a 100gr',
  'Canela Amazon¡a 250 gr.',
  'Canela Amazon¡a 500 gr.',
  'Canela especia 20 gr.',
  'Canoas Indios',
  'Caramelo echimiel',
  'Caramelo jengi bomb',
  'Caramelo Propomiel',
  'Caramelos echimiel (caja 13u)',
  'Caramelos Mielos (con propoleo y jengibre)',
  'Caramelos propomiel/jengibomb (caja 15u)',
  'Cardamomo 50g',
  'Cargo cr‚dito corriente',
  'Cartera copo',
  'Cartera de paja',
  'Cartera de semillas',
  'Cartera de tsapa',
  'Carteras de semillas (+ de 14 rombos)',
  'Carteras hexagonales y con fleco',
  'Carteras peque¤as semillas',
  'Cart¢n de Exportaci¢n (40 lbs.)',
  'Cart¢n de Jab¢n s¢lido 100u. Master De 280 260 160 T200 . ',
  'Cart¢n de Jarabe de jengibre Corrugado 24 u.',
  'Cart¢n de T‚ Corrugado para Cajas',
  'Casa andina mini',
  'Casa chonta',
  'Casa incienso',
  'Ceniceros de chonta shuar',
  'Cernidor',
  'Chal rayado',
  'Chankin 15 a 20 cm',
  'Chankin 21 a 30 cm',
  'Chankin 31 a 40 cm',
  'Chankin 41 cm en adelante',
  'Chankin hasta 14 cm',
  'CHARQUI AHUMADO (CARNE DE CERDO AHUMADA Y SECA)',
  'CHARQUI AHUMADO (CARNE DE CERDO PICANTE AHUMADA Y SECA)',
  'CHARQUI AHUMADO (CARNE DE RES AHUMADA Y SECA)',
  'CHARQUI AHUMADO (CARNE DE RES PICANTE AHUMADA Y SECA)',
  'Chia',
  'CHIA CAMARI 500gr.',
  'Chifles Conferib',
  'Chimborazos',
  'Choco crema de macadamia',
  'Choco Monedas 18GR',
  'Choco paletas',
  'Choco perlitas (almendra. pasas. uvilla',
  'Chococafe 100Gr Nacional-ORGANICO',
  'Chocolate caja triangular maracuy  120gr',
  'Chocolate caja triangular p jaro azul 120gr',
  'Chocolate caja triangular rocoto',
  'Chocolate choco Nuse 10gr',
  'Chocolate Choco Nuse 10gr',
  'Chocolate en polvo',
  'Chocolate en polvo KALLARI',
  'Chocolate hoja Verde bombones',
  'Chocolate hoja verde natural',
  'Chocolate hoja verde org nico',
  'Chocolate KALLARI 70%',
  'Chocolate KALLARI 75%',
  'Chocolate KALLARI 85%',
  'Chocolate maracuy  15gr ',
  'Chocolate mix sabores 150gr',
  'Chocolate negro con aj¡ e Ishpingo 72% SACHA ',
  'Chocolate negro con banano 73% SACHA ',
  'Chocolate negro con caf‚ tostado 60% SACHA ',
  'Chocolate negro con hierba luisa 61% SACHA ',
  'Chocolate negro con jengibre y sal Andina 71% SACHA ',
  'Chocolate negro con lim¢n y sal Andina 62% SACHA ',
  'Chocolate negro con naranja 63% SACHA ',
  'Chocolate negro con pi¤a 77% SACHA ',
  'Chocolate negro con trocitos cacao y sal Andina SACHA 80%',
  'Chocolate negro con vainilla 70% SACHA ',
  'Chocolate negro con vainilla 75% SACHA ',
  'Chocolate negro con vainilla 75% SACHA',
  'Chocolate negro con vainilla 85% SACHA',
  'Chocolate negro Selva Dorada 80%',
  'Chocolate pacari(banana.expreso beans.guava.cacao org nico',
  'Chocolate pajaro azul/trufa/menta/wiski/ron/aj¡',
  'Chocolate puro CPS',
  'Chozas macabeas grandes',
  'Chozas macabeas peque¤as',
  'Chuchuguazo ¬ libra',
  'Chuchuguazo lb.',
  'Chulpi',
  'Chulpi 50gr',
  'Chupete Echipileo-P (caja 5 unidades)',
  'Chupete Echipoleo',
  'Chuspa',
  'Chuspas',
  'Cinta de Embalaje Caf‚',
  'Cinta de Embalaje Transparente',
  'Cinta Transparente Delgada',
  'Cintillo de lona',
  'Cintur¢n de kumai',
  'Cintur¢n de semillas',
  'CIRIOS',
  'Cloro Kilo',
  'Cloruro de Sodio gr.',
  'Coctel Amaz¢nico 250ml',
  'Coctel Amaz¢nico 750ml',
  'Cofre de chonta',
  'Cojines',
  'Cola',
  'Cola (coca cola/tropical)',
  'COLA (fioravanti/fantal/ manzana)',
  'COLA (INCA/seven up)',
  'Collar cadena',
  'Collar cola de pavo',
  'Collar con guaya',
  'Collar con hilo memoria y tagua',
  'Collar cord¢n con colgante de semilla',
  'Collar de 1 hilo corto',
  'Collar de 1 hilo largo',
  'Collar de 2 hilos',
  'Collar de 3 hilos',
  'Collar de 4 hilos',
  'Collar de etse y hueso',
  'Collar de jaboncillo y guaya',
  'Collar de kumai 1 hilo',
  'Collar de kumai 3 hilos',
  'Collar de mullos',
  'Collar de tagua con hilo tejido',
  'Collar hilo cord¢n',
  'Collar hilo cord¢n tejido',
  'Collar huallca plata 925',
  'Collar memoria',
  'Collar perfumero o pirograbado',
  'Collar puim',
  'Collar redondo peque¤o',
  'Collar redondo y 3 puntas',
  'Collar semilla y plumas',
  'Collar tagua con alpaca',
  'Collar y manilla',
  'Collares',
  'Collares con dige de coco',
  'Collares con dige de tagua',
  'Collares de tagua',
  'Colonias ',
  'Colorante Amarillo gr.',
  'Colorante Rojo gr.',
  'Colorante Verde Esmeralda gr.',
  'Combustibles y lubricantes',
  'Consumo de energia el‚ctrica',
  'Consumo de internet',
  'Consumo de servicios b sico (agua)',
  'Consumo telef¢nico',
  'Control de plagas',
  'Copa larga ',
  'Copas de chonta',
  'Coppa 100gr',
  'Corona suku',
  'Coronitas de tagua',
  'Corteza de ishpink convencional',
  'Corteza de ishpink corte t‚ org nico kg.',
  'Corteza de ishpink deshidratada org nica',
  'Corteza de ishpink especia convencional',
  'Corteza de ishpink',
  'Corteza de ishpink',
  'Corteza de ishpink',
  'Crema  Fluida Org nica de Ungurahua-C¡tricos 210ml',
  'Crema de avellana',
  'Crema de cera de abeja 110gr',
  'Crema de cera de abejas 45gr',
  'Crema de cera de abejas 8gr',
  'CREMA DE CHOCOAVELLANAS',
  'Crema de jalea Real 8gr',
  'Crema fluida humectante l¡quido 75ml.',
  'Crema fluida multivitaminica ikiam hierba luisa 210ml.',
  'Crema fluida multivitaminica ikiam hierba luisa gal¢n',
  'Crema fluida multivitaminica ikiam jengibre 210ml.',
  'Crema fluida multivitaminica ikiam jengibre gal¢n',
  'Crema Fluida Org nica De Ungurahua-Citricos',
  'Crema Fluida Org nica De Ungurahua-Hierba Luisa',
  'Crema Fluida Org nica De Ungurahua-Jengibre',
  'Crema nutritiva ikiam curcuma 50ml.',
  'Crema nutritiva ikiam curcuma gal¢n',
  'Crema nutritiva ikiam hierba luisa 50ml.',
  'Crema nutritiva ikiam hierba luisa gal¢n',
  'Crema Nutritiva Org nica De Ungurahua-Curcuma',
  'Crema Nutritiva Org nica De Ungurahua-Hierba Luisa',
  'Crema Nutritiva Org nica De Ungurahua-Ishpink',
  'Crema Nutritiva Org nica de Ungurahua-Ishpink 50ml',
  'Crema untable de coco Life Choice',
  'Crodamol Ipp / Estol 1517 gr.',
  'Crodamol STS gr.',
  'Crodasinic Ls 30 gr.',
  'Crodazosoft DBQ gr.',
  'Crothix Liquid gr.',
  'Crovol Pk 70 gr.',
  'Cruz de cer mica grande',
  'Cruz de cer mica peque¤a',
  'Cuadros shuar',
  'Cucharas de chonta',
  'Cuchillos de chonta',
  'Cuchillos peque¤os chonta',
  'Cucuruchos',
  'C£rcuma deshidratada convencional kg.',
  'C£rcuma deshidratada org nica kg.',
  'C£rcuma fresca con certificaci¢n org nica KIWA BCS OKO G lb.',
  'C£rcuma fresca convencional lb.',
  'C£rcuma',
  'C£rcuma',
  'C£rcuma',
  'C£rcuma',
  'Danfat Ind-5327 gr.',
  'Danzante chico',
  'Dehyquart A gr.',
  'Denarios',
  'Desecho de man¡',
  'Desechos jabones solidos',
  'Desengrasante kilos',
  'Destilaci¢n en la comunidad',
  'Detergente Kilos',
  'Difusores (hongo)',
  'Display Barra 66% + Naranja 50gr',
  'Display Barra avellana 35g -NATURAL',
  'Display Barra capuccino 35g -NATURAL',
  'Display Barra Chocoquinua 50% 35Gr',
  'Display Barra Chocoquinua dark 35Gr',
  'Display Barra guayaba 35g -NATURAL',
  'Display Barra lim¢n 35g-Natural',
  'Display Barra mandarina 35g -NATURAL',
  'Display Barra maracuy  35g -NATURAL',
  'Display Barra menta 35g -NATURAL',
  'Display Barra pi¤a colada 50gr',
  'Display Barra Tequila Sour-50Gr ',
  'Display Barra vainilla 35g -NATURAL',
  'Display Barra Whisky-50Gr ',
  'Display Barras Chia',
  'Display Barras Nacional 50gr  58%',
  'Display Barras Nacional 50gr 100%',
  'Display Barras Nacional 50gr 66%',
  'Display Barras Nacional 50gr 72%',
  'Display Barras Nacional 50gr 80%',
  'Display Barras Nacional 50gr Leche 50%',
  'Display Barras Quinua',
  'Dosificador 18/410',
  'Dosificador de Aceite masaje 24/410 Blanca Y.C.',
  'Dosificador de Jab¢n l¡quido 28/410 Zf. ',
  'Dow Corning 200 gr./XI PMX 200-350 cSt',
  'Dulce de Mora',
  'Dulce noche 60ml',
  'EDEBEON LENGUA Y LITERATURA BGU1',
  'EDEBEON LENGUA Y LITERATURA BGU2',
  'EDEBEON LENGUA Y LITERATURA BGU3',
  'EDEBEON LENGUA Y LITERATURA EGB10',
  'EDEBEON LENGUA Y LITERATURA EGB3',
  'EDEBEON LENGUA Y LITERATURA EGB4',
  'EDEBEON LENGUA Y LITERATURA EGB5',
  'EDEBEON LENGUA Y LITERATURA EGB6',
  'EDEBEON LENGUA Y LITERATURA EGB7',
  'EDEBEON LENGUA Y LITERATURA EGB8',
  'EDEBEON LENGUA Y LITERATURA EGB9',
  'EDEBEON MATEMATICA BGU1',
  'EDEBEON MATEMATICA BGU2',
  'EDEBEON MATEMATICA BGU3',
  'EDEBEON MATEMATICA EGB10',
  'EDEBEON MATEMATICA EGB3',
  'EDEBEON MATEMATICA EGB4',
  'EDEBEON MATEMATICA EGB5',
  'EDEBEON MATEMATICA EGB6',
  'EDEBEON MATEMATICA EGB7',
  'EDEBEON MATEMATICA EGB8',
  'EDEBEON MATEMATICA EGB9',
  'EDEBEON ZAIN 10',
  'EDEBEON ZAIN 2',
  'EDEBEON ZAIN 3',
  'EDEBEON ZAIN 4',
  'EDEBEON ZAIN 5',
  'EDEBEON ZAIN 6',
  'EDEBEON ZAIN 7',
  'EDEBEON ZAIN 8',
  'EDEBEON ZAIN 9',
  'EDEBEON ZAIN BGU1',
  'EDEBEON ZAIN BGU2',
  'EDEBEON ZAIN BGU3',
  'ELE 2 EDUCACIàN INICIAL',
  'Emulgade 1000 Ni gr.',
  'Emulgate 100 NI / Polawax gr.',
  'Envase de Aceite esencial 50ml. Ambar ',
  'Envase de Aceite esencial de Aluminio 33.3 Oz.',
  'Envase de Aceite esencial de Vidrio Ambar De 1 Lt.',
  'Envase de Aceite esencial de Vidrio Ambar De 10 ml.',
  'Envase de Aceite esencial de Vidrio Ambar De 5 ml.',
  'Envase de Aceite masaje-repelente Pet 4 Oz (120 Ml) B.T.',
  'Envase de Body splash Pet Cilindrico 150 Ml Yc.',
  'Envase de Crema fluida Pet 210 Ml Torre + Df Y. C.',
  'Envase de Crema fluida Pet Jordy 75 ml TC / CF.',
  'Envase de Crema nutritiva Pote 50 Ml Pp Tapa Blanca Y. C.',
  'Envase de Gal¢n Rectangular 4000ml Blanco',
  'Envase de Jab¢n l¡quido Pet 500 Ml Alfa D.P. ',
  'Envase de Jab¢n l¡quido Pet Bolita 300 Ml Transparente B.T. ',
  'Envase de Jarabe jengibre Frascos Ambar De 120 ml.',
  'Envase de miel abeja 370ML S-JAR ROUND C-03370 incluye tapa',
  'Envase de Sangre de drago Dp-21 Fgp Tipo Gotero 2c Onz.Pl.',
  'Envase de Shampoo Pet 250 Ml Trans B.T.',
  'Envase de Shampoo Pet Jorgy 275 Ml Trans B.T.',
  'Envase de Shampoo Pet Jorgy 30 Ml Trans B.T.',
  'Envase de Shampoo Pet plano 60ml T/20',
  'Envase de Wapa Dp-52 M Merm. De 1/2 Lb. Pet. Tr',
  'Envase Efa-72b Env. Agroquim.10000.C.Pet.Bl',
  'Envase Pep De 1/2 Lts.',
  'Envase Poma 20 Lts.',
  'Envase Poma 40 Lts.',
  'Envases',
  'Envio de mercader¡a',
  'Escoba',
  'ESEMTIA UEFDON BOSCO MACAS',
  'ESEMTIA UEFDON BOSCO MACAS (inicial)',
  'Esferas decorativas',
  'Esferos de balsa',
  'Esponja de Empaque',
  'Esquinero',
  'Estrella fieltro',
  'Etiqueta de Aceite de masajes de ishpink',
  'Etiqueta de Aceite de masajes de jengibre',
  'Etiqueta de Aceite de masajes de mandarina',
  'Etiqueta de Aceite de masajes de naranja',
  'Etiqueta de Aceite de ungurahua',
  'Etiqueta de Aceite esencial de c£rcuma',
  'Etiqueta de Aceite esencial de hierba luisa',
  'Etiqueta de Aceite esencial de ishpink',
  'Etiqueta de Aceite esencial de jengibre',
  'Etiqueta de Aceite esencial de lima',
  'Etiqueta de Aceite esencial de limon',
  'Etiqueta de Aceite esencial de mandarina',
  'Etiqueta de Aceite esencial de naranja',
  'Etiqueta de Aceite esencial de toronja',
  'Etiqueta de Aceite repelente',
  'Etiqueta de Acondicionador de romero 60ml.',
  'Etiqueta de Acondicionador de ungurahua hl 250ml.(anverso - ',
  'Etiqueta de Acondicionador de ungurahua hl 270ml.(anverso - ',
  'Etiqueta de Acondicionador de ungurahua romero 250ml. (anver',
  'Etiqueta de Acondicionador de ungurahua romero 270ml. (anver',
  'Etiqueta de Aj¡ con sal',
  'Etiqueta de Aj¡ de 25 gramos',
  'Etiqueta de Albahaca especia',
  'Etiqueta de Body splash de c¡tricos',
  'Etiqueta de Body splash de c£rcuma',
  'Etiqueta de Body splash de ishpink',
  'Etiqueta de Body splash de jengibre',
  'Etiqueta de Canela 100 gr.',
  'Etiqueta de Canela corteza 10 gr.',
  'Etiqueta de Canela corteza 250 gr.',
  'Etiqueta de Canela corteza 500 gr.',
  'Etiqueta de Chuchuguazo',
  'Etiqueta de Crema fluida Hierba Luisa 60ml.',
  'Etiqueta de Crema fluida multivitaminica de hierba luisa (an',
  'Etiqueta de Crema fluida multivitaminica de jengibre (anvers',
  'Etiqueta de Crema Fluida Org nica De Ungurahua-Citricos',
  'Etiqueta de Crema Fluida Org nica de Ungurahua-Citricos COSM',
  'Etiqueta de Crema Fluida Org nica De Ungurahua-Hierba Luisa',
  'Etiqueta de Crema Fluida Org nica de Ungurahua-Hierba Luisa ',
  'Etiqueta de Crema Fluida Org nica De Ungurahua-Jengibre',
  'Etiqueta de Crema Fluida Org nica de Ungurahua-Jengibre COSM',
  'Etiqueta de Crema nutritiva de c£rcuma',
  'Etiqueta de Crema nutritiva de hierba luisa',
  'Etiqueta de Crema Nutritiva Org nica De Ungurahua-Curcuma',
  'Etiqueta de Crema Nutritiva Org nica de Ungurahua-C£rcuma CO',
  'Etiqueta de Crema Nutritiva Org nica De Ungurahua-Hierba Lui',
  'Etiqueta de Crema Nutritiva Org nica de Ungurahua-Hierba Lui',
  'Etiqueta de Crema Nutritiva Org nica De Ungurahua-Ishpink',
  'Etiqueta de Crema Nutritiva Org nica de Ungurahua-Ishpink CO',
  'Etiqueta de Crema Nutritiva Org nica redonda',
  'Etiqueta de C£rcuma especia',
  'Etiqueta de Gel analg‚sico (anverso - reverso)',
  'Etiqueta de Gel oriente (anverso - reverso)',
  'Etiqueta de Infusi¢n de guayusa',
  'Etiqueta de Infusi¢n de guayusa e ishpink',
  'Etiqueta de Infusi¢n de guayusa org nica',
  'Etiqueta de Infusi¢n de hierba luisa',
  'Etiqueta de Infusi¢n de hierba luisa e ishpink',
  'Etiqueta de Infusi¢n de hierba luisa y jengibre',
  'Etiqueta de Infusi¢n de hl. guayusa. jengibre e ishpink',
  'Etiqueta de Jab¢n hotelero s¢lido array n y piedra',
  'Etiqueta de Jab¢n hotelero s¢lido c£rcuma y hierba luisa  (f',
  'Etiqueta de Jab¢n liquido curcuma 60ml.',
  'Etiqueta de Jab¢n l¡quido de c£rcuma 300ml.',
  'Etiqueta de Jab¢n l¡quido de c£rcuma 500ml. (anverso - rever',
  'Etiqueta de Jab¢n l¡quido de hierba luisa 300ml.',
  'Etiqueta de Jab¢n l¡quido de hierba luisa 500ml. (anverso - ',
  'Etiqueta de Jab¢n l¡quido de ishpink 300ml.',
  'Etiqueta de Jab¢n l¡quido de ishpink 500ml. (anverso - rever',
  'Etiqueta de Jab¢n l¡quido de lim¢n 300ml.',
  'Etiqueta de Jab¢n l¡quido de lim¢n 500ml. (anverso - reverso',
  'Etiqueta de Jab¢n s¢lido de ishpink exportaci¢n',
  'Etiqueta de Jab¢n s¢lido de jengibre exportaci¢n',
  'Etiqueta de Jab¢n s¢lido de lim¢n exportaci¢n',
  'Etiqueta de Jab¢n s¢lido Hierba Luisa 30ml.',
  'Etiqueta de Jab¢n s¢lido ikiam  lim¢n 100gr.',
  'Etiqueta de Jab¢n s¢lido ikiam  lim¢n 12gr.',
  'Etiqueta de Jab¢n s¢lido ikiam  palo santo 100gr.',
  'Etiqueta de Jab¢n s¢lido ikiam c£rcuma y hierba luisa 12gr.',
  'Etiqueta de Jab¢n s¢lido ikiam c£rcuma y mandarina 100gr.',
  'Etiqueta de Jab¢n s¢lido ikiam c£rcuma y mandarina 12gr.',
  'Etiqueta de Jab¢n s¢lido ikiam c£rcumayhierba luisa100gr.',
  'Etiqueta de Jab¢n s¢lido ikiam hierba luisa 100gr.',
  'Etiqueta de Jab¢n s¢lido ikiam hierba luisa 12gr.',
  'Etiqueta de Jab¢n s¢lido ikiam ispink 100 gr.',
  'Etiqueta de Jab¢n s¢lido ikiam ispink 12gr.',
  'Etiqueta de Jab¢n s¢lido ikiam jengibre 100gr.',
  'Etiqueta de Jab¢n s¢lido ikiam jengibre 12gr.',
  'Etiqueta de Jab¢n s¢lido ikiam sangre de drago 100gr.',
  'Etiqueta de Jarabe de jengibre de adultos',
  'Etiqueta de Jarabe de jengibre de ni¤os',
  'Etiqueta de Jengibre especia',
  'Etiqueta de Man¡ tostado de 250 gramos',
  'Etiqueta de sangre de drago CONVENCIONAL',
  'Etiqueta de Sangre de drago org nico',
  'Etiqueta de Shampoo de romero 60ml.',
  'Etiqueta de Shampoo de ungurahua 30ml.(anverso - reverso)',
  'Etiqueta de Shampoo de ungurahua hl 250ml.(anverso - reverso',
  'Etiqueta de Shampoo de ungurahua hl 270ml.(anverso - reverso',
  'Etiqueta de Shampoo de ungurahua romero 250ml. (anverso - re',
  'Etiqueta de Shampoo de ungurahua romero 270ml. (anverso - re',
  'Etiqueta de Tapa crema nutritiva',
  'Etiqueta de U¤a de gato',
  'Etiqueta de Wapas',
  'Etnias',
  'Euperlan Pk3000 gr.',
  'Extracto Etan¢lico de Chuchuguazo',
  'Extracto Etan¢lico de Guayusa',
  'Extracto Etan¢lico de Jengibre',
  'Extrapon Manzanilla gr.',
  'Fachada compleja chica',
  'Figuras en fieltro',
  'Flauta',
  'Flechas de chonta',
  'Flechas para la tunta',
  'Flor de jamaica lb.',
  'Florero de chonta',
  'Florero de chonta grande',
  'Flores ',
  'Fragancia para carro ',
  'Frasco de Aceite De Cosedora',
  'Fresh tea jamaica/c£rcuma-jengibre/cardamomo/ moringa jengib',
  'Frumix 100gr',
  'Frumix 200gr',
  'Frumix almendra y pi¤a 100g',
  'Frumix Almendra y pi¤a 50gr',
  'Frumix almendras y pi¤a 50g',
  'Frumix nueces y pi¤a deshidratada 50gr',
  'Frumix pi¤a deshidratada',
  'Frutos secos 100gr',
  'Frutos secos 200gr',
  'Frutos secos 50gr',
  'Frutos secos 80gr',
  'Frutos secos grandes',
  'Frutos secos peque¤os',
  'Funda de Especia De Polipropileno Monorientado 8cmX12cm',
  'Funda de Man¡ Polietileno De Alta Densidad',
  'Funda de Papel # 12 (man¡)',
  'Funda de Planta Arom ti Polipropileno Monorientado 11cmX15cm',
  'Funda de Polifan 6x10 Cm',
  'Funda pl stica',
  'Funda Quintalera',
  'Fundas papel reciclado',
  'Fuze tea',
  'Galletas de avena',
  'Galletas de Soya 30gr',
  'Galletas Digestive con Arandanos',
  'Galletas Digestive con avena 190gr',
  'Galletas Digestive originales 190gr',
  'Galletas Disgestive con cacao 200gr',
  'Galletas monasterio',
  'Gargantilla un hilo',
  'Gatos fieltro',
  'Gel an lgesico 300gr.',
  'Gel an lgesico 500gr.',
  'Gel analg‚sico y antiinflamatorio',
  'Gel oriente',
  'Glicerina Usp gr.',
  'Grageas Almendras 45gr',
  'Grageas Uvilla 45gr',
  'Granola 250gr',
  'Granola 450 gr',
  'Granola con stevia',
  'Granola frutas y semillas',
  'Guante de Caucho',
  'Guante de Nitrato Medium',
  'Guantes fieltro',
  'Guayusa deshidratada',
  'Guayusa e ishpink 35gr.',
  'Guayusa en corte de T‚ kg.',
  'Guayusa Natural 35 gr.',
  'Guayusa Org nica 35 gr.',
  'GUESS WHAT FOR ECUADOR STUDENTS BOOK AND',
  'Gitic',
  'Habas (dulce) 100 gr.',
  'Habas 150gr',
  'Habas 150gr',
  'Habas con sal',
  'HABAS SALADITAS CAMARI 100gr',
  'HARINA DE ALMENDRAS 200G',
  'Harina de Chocho 250gr',
  'Harina de Chocho y Avena 250gr',
  'Harina de Coco ',
  'Harina de Maca 225gr',
  'Harina de Maca y Quinua 250gr',
  'Harina de Platano 450 gr.',
  'Harina de quinua 250gr',
  'Harina de Quinua 500gr',
  'Harina de soya. quinua. cebada y avena (Mama Luca)',
  'Harina de Yuca 450 gr.',
  'Hebilla Plastica Y Met licas',
  'Hidr¢xido de Sodio gr.',
  'Hierba luisa  35gr.',
  'Hierba Luisa deshidratada kg.',
  'Hierba luisa e ishpink 35gr.',
  'Hierba luisa y jengibre 35gr.',
  'Hojas de canela achuar lb.',
  'Hojas de canela lb.',
  'Hojas de guayusa con certificaci¢n org nica KIWA BCS OKO lb.',
  'Hojas de Guayusa deshidratadas organico',
  'Hojas de guayusa lb.',
  'Hojas de hierba Luisa achuar lb.',
  'Hojas de hierba luisa org nico lb.',
  'Hojas de lim¢n lb.',
  'Hojas de naranja achuar lb.',
  'Hongos secos',
  'Honorarios profesionales',
  'Horchatas',
  'Huamboyitas 50gr(natural)',
  'Imanes de balsa',
  'Imanes de balsa',
  'Inciencio',
  'Ind¡gena aromaterapia',
  'Indigena chico',
  'Indigena mediano',
  'Indios',
  'Infusi¢n de guayusa & canela Amazon¡a. cajita de t‚.',
  'Infusi¢n de guayusa Amazon¡a. cajita t‚.',
  'Infusi¢n de guayusa. ishpink y lim¢n Amazon¡a. cajita t‚.',
  'Infusi¢n de hierba luisa & ishpink Amazon¡a. cajita de t‚.',
  'Infusi¢n de hierba luisa & jamaica Amazon¡a. cajita de t‚.',
  'Ishpink c liz especia 20 gr.',
  'Ishpink corteza con certificaci¢n org nica KIWA BCS OKO',
  'Ishpink corteza convencional',
  'Ishpink corteza especia convencional en kg.',
  'Ishpink.hierbaluisa.guayusa.jengibre 35gr.',
  'Itinkiat(olla de barro)',
  'Itip',
  'Jab¢n de cuerpo s¢lido Hierba Luisa barra 30gr.',
  'Jab¢n l¡quido c£rcuma 60ml.',
  'Jab¢n l¡quido ikiam curcuma 300ml.',
  'Jab¢n l¡quido ikiam curcuma 500ml.',
  'Jab¢n l¡quido ikiam c£rcuma gal¢n',
  'Jab¢n l¡quido ikiam hierba luisa 300ml.',
  'Jab¢n l¡quido ikiam hierba luisa 500ml.',
  'Jab¢n l¡quido ikiam hierba luisa gal¢n',
  'Jab¢n l¡quido ikiam ishpink 300ml.',
  'Jab¢n l¡quido ikiam ishpink 500ml.',
  'Jab¢n l¡quido ikiam ishpink gal¢n',
  'Jab¢n l¡quido ikiam limon 300ml.',
  'Jab¢n l¡quido ikiam limon 500ml.',
  'Jab¢n l¡quido ikiam lim¢n gal¢n',
  'Jab¢n Macho',
  'Jab¢n s¢lido barra gramos',
  'Jab¢n s¢lido ikiam 17 gr.',
  'Jab¢n s¢lido ikiam c£rcuma y hierba luisa 100gr.',
  'Jab¢n s¢lido ikiam c£rcuma y hierba luisa 15gr.',
  'Jab¢n s¢lido ikiam c£rcuma y mandarina 100gr.',
  'Jab¢n s¢lido ikiam c£rcuma y mandarina 15gr.',
  'Jab¢n s¢lido ikiam hierba luisa 100gr.',
  'Jab¢n s¢lido ikiam hierba luisa 15gr.',
  'Jab¢n s¢lido ikiam ispink 100 gr.',
  'Jab¢n s¢lido ikiam ispink 15gr.',
  'Jab¢n s¢lido ikiam jengibre 100gr.',
  'Jab¢n s¢lido ikiam jengibre 15gr.',
  'Jab¢n s¢lido ikiam lim¢n 100gr.',
  'Jab¢n s¢lido ikiam lim¢n 15gr.',
  'Jab¢n s¢lido ikiam palo santo 100gr.',
  'Jab¢n s¢lido ikiam palo santo 15gr.',
  'Jab¢n s¢lido ikiam sangre de drago 100 gr.',
  'Jab¢n s¢lido ikiam sangre de drago 15 gr.',
  'Jab¢n s¢lido Natyr Canella 100 g',
  'Jabon s¢lido Natyr Limone 100 g',
  'Jabon s¢lido Natyr Zenzero 100 g',
  'Jamaica deshidratada kg.',
  'Jarabe de jengibre para adultos',
  'Jarabe de jengibre para ni¤os',
  'Jengibre corte t‚ org nico. kg',
  'Jengibre deshidratado (sin moler) org nico kg.',
  'Jengibre deshidratado y molido org nica (especia) kg.',
  'Jengibre deshidratado y molido org nico (especia) 20 gr.',
  'Jengibre deshidratado y molido org nico (especia) en Kg.',
  'Jengibre fresco achuar convencional lb.',
  'Jengibre fresco con certificaci¢n org nica KIWA BCS OKO lb.',
  'Jengibre fresco convencional lb.',
  'Jenjibre panela 150g',
  'Jenjibre panela 50g',
  'Jes£s cer mica',
  'Juego (collar 1 hilo. aretes y manilla)',
  'Juego (collar 1vuelta. manilla. aretes y anillo)',
  'Juego (collar 2-4 hilos. aretes y manilla)',
  'Juego collar + aretes',
  'Juego de mu¤eca',
  'KAWSAY 120GR (TE DE WAKA NAWE)',
  'Lagarto de balsa',
  'L mina de Cart¢n Prensado',
  'L mina de Jab¢n s¢lido Polipropileno De 12cm X 17cm.',
  'L minas de papel reciclado',
  'L mpara',
  'L mpara Dianto',
  'L mpara Quito luz',
  'Lanza sencilla',
  'Lanzas grandes',
  'Leche de almendras',
  'Leche de soya fresa crema/ capuccino almendras',
  'Le¤a para destilaci¢n en la comunidad lbs.',
  'LENGUA Y LITERATURA OPTIMIZADO 2EGB + PLATAFORMA',
  'Libretas papel reciclado',
  'Libro',
  'Libro',
  'Libro',
  'Libro',
  'Libro',
  'Libro',
  'Libro Camino de Vida 1 BGU LNS',
  'Libro Camino de Vida 1 EGB LNS',
  'Libro Camino de Vida 10 EGB LNS',
  'Libro Camino de Vida 2 BGU LNS',
  'Libro Camino de Vida 2 EGB LNS',
  'Libro Camino de Vida 3 BGU LNS',
  'Libro Camino de Vida 3 EGB LNS',
  'Libro Camino de Vida 4 EGB LNS',
  'Libro Camino de Vida 5 EGB LNS',
  'Libro Camino de Vida 6 EGB LNS',
  'Libro Camino de Vida 7 EGB LNS',
  'Libro Camino de Vida 8 EGB LNS',
  'Libro Camino de Vida 9 EGB LNS',
  'Libro Camino de Vida Inicial LNS',
  'Libro Cantar del mio Cid plan lector',
  'Libro Ciudadania',
  'Libro de Biolog¡a',
  'LIBRO DE CIGšENAS DESPISTADAS Y PRINCESAS INTER PLAN LECT',
  'Libro de Ingl‚s',
  'Libro despierta Mart¡n',
  'LIBRO DO¥A FLAUTINA RESUELVELO TODO (PLAN LECTOR +CUAD. ACT)',
  'LIBRO EL DOMADOR MIEDOSO (PLAN LECTOR +CUAD. ACT)',
  'LIBRO EL ENANO GUMERSINDO(PLAN LECTOR +CUAD. ACT)EL',
  'LIBRO EL MONSTRUO DEL BAUL',
  'LIBRO EL REGRESO DEL CONDOR',
  'Libro El tren de los fantasmas y la montana encantada LNS',
  'LIBRO EL VIAJE DE NABIL LIBRO CUAD DE ACT',
  'LIBRO EL VIAJE DE NABIL(PLAN LECTOR +CUAD. ACT)',
  'Libro Emprendimiento y gesti¢n',
  'Libro English In Common Split 1A Sband Wb Wmyenglishla Pears',
  'Libro English In Common Split 1B Sband Wb Wmyenglishla Pears',
  'Libro English In Common Split 2A Sband Wb Wmyenglishla Pears',
  'Libro English In Common Split 2B Sband Wb Wmyenglishla Pears',
  'Libro English In Common Split 3A Sband Wb Wmyenglishla Pears',
  'Libro English In Common Split 3B Sband Wb Wmyenglishla Pears',
  'Libro Entranables Libro Cuad Act LNS',
  'LIBRO ENTREVISTA EN LAS ALTURAS LIBRO CUAD ACT',
  'LIBRO EPISODIOS FUTURISTAS CUAD ACT',
  'Libro Filosof¡a 1 BGU',
  'Libro Filosof¡a 2 BGU',
  'Libro Historia 1BGU',
  'Libro Historia 2BGU',
  'LIBRO HOJAS DE MARZO LIBRO CUAD ACT',
  'Libro Investigaci¢n y ciencia de la tecnologia',
  'LIBRO JON Y LA MAQUINA DEL MIEDO PLAN LECTOR CUAD ACT',
  'Libro La casa del Acantilado cuad. act.',
  'LIBRO LA JOVEN DE LA MEDIANOCHE (PLAN LECTOR +CUAD. ACT)',
  'Libro la leyenda del Arupo y otros relatos LNS (libro +cuade',
  'LIBRO LA OVEJA DISTINTA Y OTROS CUENTOS LIBRO CUAD ACT',
  'LIBRO LAZARILLO DE TORMES PLAN LECTOR',
  'Libro Los Ladrones De Colores Plan Lector Cuad Act LNS',
  'Libro los L pices M gicos de Andrea LNS (libro+cuaderno)',
  'Libro Los Palacios caidos libro cuad act LNS',
  'Libro los Perfectos LNS (plan lector + cuaderno act.)',
  'LIBRO MENTIRA (PLAN LECTOR +CUAD. ACT)',
  'LIBRO MI ABUELO EL PRESUNTO (PLAN LECTOR +CUAD. ACT)',
  'Libro mi hermano el Genio LNS (Plan Lector + cuaderno)',
  'Libro mitos',
  'Libro Prohibido tener catorce anos plan lector cuad act LNS',
  'Libro Quieres ser el novio de mi hermana plan lector LNS',
  'LIBRO RUTINDEL (PLAN LECTOR +CUAD. ACT)',
  'Libro Se ofrece chico plan lector',
  'Libro Se ofrece chico Plan Lector cuad. act.',
  'LIBRO UNCOVER FOR ECUADOR 1A',
  'LIBRO UNCOVER FOR ECUADOR 1B',
  'LIBRO UNCOVER FOR ECUADOR 2A',
  'LIBRO UNCOVER FOR ECUADOR 2B',
  'LIBRO UNCOVER FOR ECUADOR 3A',
  'LIBRO UNCOVER FOR ECUADOR 3B',
  'Libro Y Ahora que plan lector cuad act LNS',
  'LIBRO ZAIN 10EGB COMBO COMPLETO + PLATAFORMA',
  'LIBRO ZAIN 1BGU COMBO COMPLETO + PLATAFORMA',
  'LIBRO ZAIN 2BGU COMBO COMPLETO + PLATAFORMA',
  'LIBRO ZAIN 3BGU COMBO COMPLETO + PLATAFORMA',
  'LIBRO ZAIN 8EGB COMBO COMPLETO + PLATAFORMA',
  'LIBRO ZAIN 9EGB COMBO COMPLETO + PLATAFORMA',
  'LIBRO ZAIN TEXTO + L PEREGRINO 1EGB',
  'LIBRO ZAIN TEXTO + L PEREGRINO 2EGB',
  'LIBRO ZAIN TEXTO + L PEREGRINO 3EGB',
  'LIBRO ZAIN TEXTO + L PEREGRINO 3EGB',
  'LIBRO ZAIN TEXTO + L PEREGRINO 4EGB',
  'LIBRO ZAIN TEXTO + L PEREGRINO 5EGB',
  'LIBRO ZAIN TEXTO + L PEREGRINO 6EGB',
  'LIBRO ZAIN TEXTO + L PEREGRINO 7EGB',
  'Libros Educativos',
  'Libros Historia',
  'Libros Quimica',
  'Linaza (pitahaya; frutos rojos; pi¤a ciruela) 450gr',
  'LINAZA CAMAR 500gr.',
  'Linaza frutos rojos 450gr (Umar¡)',
  'Linaza natural molida 450gr (Umar¡)',
  'Linaza pi¤a y ciruela 450gr (Umar¡)',
  'Lipacide C8g ml.',
  'Llavero de semillas',
  'Llavero masapan',
  'Llaveros ',
  'Llaveros de balsa',
  'Llaveros de tagua',
  'Llaveros de tagua y kumai',
  'Loncheras nutritivas 100gr',
  'Lonza 100gr',
  'Loras dobles',
  'Loro coraz¢n',
  'Loro peque¤o de balsa',
  'Loro porta esferos',
  'Loro y tucan 10cm',
  'Loro y tuc n 15cm',
  'Loro y tuc n 30cm',
  'Loro y tucan 6cm',
  'Loro y tucan 8cm',
  'Loros 20 cm',
  'Loros 50 cm',
  'Loros de pared',
  'Loros especiales 30 cm',
  'Lufas',
  'Lustre Inoxidable',
  'M- Akuamed (Antimicrobial)',
  'Macabeos',
  'Macadamias',
  'Machete de chonta',
  'Makich',
  'Man¡ achuar con certificaci¢n org nica KIWA BCS OKO GARA lb.',
  'Man¡ achuar convencional lb.',
  'Man¡ Conferib',
  'Man¡ confitado 150g',
  'Man¡ convencional',
  'Man¡ garapi¤ado 150g',
  'Man¡ garapi¤ado 50 gr.',
  'Man¡ garapi¤ado 60 gr. Chankuap',
  'Man¡ natural zona transkutuku (materia prima)',
  'Man¡ org nico',
  'Man¡ shuar con certificaci¢n org nica KIWA BCS OKO GARAN lb.',
  'Man¡ shuar convencional lb.',
  'Man¡ tostado org nico 250 gr.',
  'Man¡ tostado org nico kg.',
  'Manilla 2 hilos el stico',
  'Manilla con anillo',
  'Manilla de hilo encerado',
  'Manilla de kumai 2 hilos',
  'Manilla de kumai 4 hilos',
  'Manilla de kumai 6 hilos',
  'Manilla de semillas 10 hilos',
  'Manilla de semillas 2 hilos',
  'Manilla de semillas 4 hilos',
  'Manilla de semillas 5 hilos',
  'Manilla de un hilo corrido',
  'Manilla memoria',
  'Manilla mullos',
  'Manillas',
  'Manillas con guaya',
  'Manillas de tagua',
  'Manillas pambil',
  'Manjar de leche con coco ',
  'Manteca de cacao con certificaci¢n org nica gr.',
  'Manteca de cacao gr.',
  'Mantenimiento de veh¡culo',
  'MANTEQUILLA DE ALM/COCO',
  'Mantequilla de almendra life choice',
  'Mantequilla de man¡ Life Choice 200g',
  'Mantequilla de man¡ Life Choice 490g',
  'Maracas Grandes',
  'Maracas Peque¤as',
  'Mariposa inciencio',
  'Masajeadores de tagua',
  'Mascarilla Desechable',
  'Mascarilla exfoliante de miel de abejas 18gr',
  'Mascarilla exfoliante de miel de abejas 43gr',
  'MATEMATICA INGENIOS OPTIMIZADO 2EGB + PLATAFORMA',
  'Material para botiquin',
  'Merm. araz /morti¤o 140gr',
  'Merm. araz /papaya 140gr',
  'Merm. banano/maracuy /vainilla 140gr',
  'Merm. Jamaica 140gr',
  'Merm. maracuy /banano140gr',
  'Merm. zapallo/maracuy /naranja/quinua 140gr',
  'Mermelada 1/4 suc£a',
  'Metil Parabeno gr.',
  'Mezcla pancake con canela',
  'Mezcla pancake con chispas',
  'Mezcla pancakes banana verde / amarilla',
  'MEZCLA PANCAKES H. COCO CON BANANA',
  'MEZCLA PANCAKES H. COCO/CHOCOLATE',
  'Mezcla para tortitas de yuca 250gr',
  'Mezcla torta con chocolate',
  'Miel de abeja 320g',
  'Miel de abeja 450gr.',
  'Miel de abeja gr.',
  'Miel de abeja juve 620gr',
  'Miel de Ca¤a ml.',
  'Millers avena frutos rojos 300gr',
  'Millers avena hojuela sabor vainilla 300gr ',
  'Millers avena instantanea canela 300gr',
  'Millers avena instantanea fresa 200gr',
  'Millers avena instantanea vainilla 200gr',
  'MILLERS MESCLA  /PANCAKES REDU/ AZUCAR 400GR',
  'MILLERS MESCLA LISTA /PANCAKES COMPLETA 400GR',
  'MIX DE FRUTOS SECOS ',
  'Monedero de cuero',
  'Monederos de semilla',
  'Monederos exagonales',
  'Monja chica',
  'Mo¤os',
  'Monos de balsa',
  'Monos de coco',
  'Montanov 202 gr.',
  'Montanov 68 gr.',
  'Movil balsa',
  'Muestras sin valor comercial',
  'Muits peque¤a',
  'Muits peque¤¡sima',
  'Mujer aromaterapia',
  'Mujer colonial chica',
  'Mujeres campana/ mujeres inciencio mini',
  'Mu¤eca peque¤as',
  'Nacimiento Dianto',
  'Nacimiento masapan',
  'Nacimiento Tagua',
  'NC POR DESCUENTO',
  'Nibs de cacao',
  'Nidos medianos',
  'Nidos peque¤os',
  'Ollas ',
  'Ollas aromaterapia',
  'PACARI ANDEAN BLUEBERRY CHOCOLATE BAR (morti¤o)',
  'PACARI CACAO EN POLVO (NATURAL)',
  'PACARI cacao nibs RAW lb',
  'PACARI CAFE CHOCOLATE BAR',
  'PACARI CARDAMOMO CHOCOLATE BAR',
  'PACARI CEDRON CHOCOLATE BAR',
  'PACARI CHERY CHOCOLATE BAR (cereza)',
  'PACARI CHIA+JENGIBRE CHOCLATE BAR',
  'PACARI chips de chocolate 60%',
  'PACARI CHOC. COVERED BANANA',
  'PACARI CHOC. COVERED ESPRESO BEANS (caf‚)',
  'PACARI CHOC. COVERED GOLDEN BERRIES',
  'PACARI CHOC. COVERED GOLDEN BERRIES (uvilla)',
  'PACARI CHOC. NIBS CUBIERTOS DE CHOCOALTE',
  'PACARI CRANBERRIES CHOCOLATE BAR (arandanos rojos)',
  'PACARI ENEBRO CHOCOLATE BAR ',
  'PACARI GOLDEN BERRIES CHOCOLATE BAR (uvilla)',
  'PACARI GUAYUSA CHOCOLATE BAR',
  'PACARI HIGO CHOCOLATE BAR',
  'PACARI JAZMIN CHOCOLATE BAR',
  'Pacari kids cocoa 250gr',
  'PACARI LEMONGRASS (hierba luisa)CHOCOLATE BAR',
  'PACARI LIMON CHOCOLATE BAR',
  'PACARI MARACUYµ  CHOCOLATE BAR',
  'PACARI MENTA CHOCOLATE BAR',
  'PACARI MERKEN-CHILI CHOCOLATE BAR (aj¡)',
  'PACARI MINI BARRA Maracuya',
  'PACARI NARANJA CHOCOLATE BAR',
  'PACARI PIMIENTA DULCE CHOCOLATE BAR',
  'PACARI premezcla para brownie',
  'PACARI ROSAS CHOCOLATE BAR',
  'PACARI SAL & NIBS CHOCOLATE BAR',
  'PACARI SPIRULINA +az£car de coco CHOCOLATE BAR (70%) ',
  'Pa¤o Verde',
  'Pa¤o verde para lavarplatos',
  'Pa¤o Vileda por 3',
  'Papa china Conferib',
  'papa china/chifles/camote mix',
  'Papel Higi‚nico',
  'Papel Peri¢dico',
  'Pasta de cacao',
  'Pasta de S‚samo Tahini',
  'pastillas aromatizantes ',
  'Patak adorno de mujer',
  'Payasitos de semillas',
  'Payasitos de semillas peque¤os',
  'Pepsi',
  'Pernillo',
  'Perros fieltro',
  'Phenova gr.',
  'Piedra de moler',
  'Pinchos de cabello',
  'Pinink de 13 a 20 cm',
  'Pinink hasta 12 cm',
  'Pinink peque¤¡sima',
  'Pinink peque¤¡sima',
  'Pinzas',
  'Pir mide aromaterapia',
  'Pir mide mini',
  'Pir mide porta esferos',
  'Pitiak de kaap adorno shuar',
  'PLATAFORMA CAMBRIDGE GUESS WHAT LEVEL 4',
  'PLATAFORMA CAMBRIDGE GUESS WHAT LEVEL 5',
  'PLATAFORMA CAMBRIDGE UNCOVER LEVEL 1 A',
  'PLATAFORMA CAMBRIDGE UNCOVER LEVEL 1 B',
  'PLATAFORMA CAMBRIDGE UNCOVER LEVEL 2 A',
  'PLATAFORMA CAMBRIDGE UNCOVER LEVEL 2 B',
  'PLATAFORMA CAMBRIDGE UNCOVER LEVEL 3 A',
  'PLATAFORMA CAMBRIDGE UNCOVER LEVEL 3 B',
  'Platanitos de sal',
  'Polen compuesto juve',
  'Polen granulado tradiciones don juve',
  'Pomadas salinas',
  'Poros',
  'Porta celular',
  'Porta celular shuar',
  'Porta cubiertos',
  'Porta esferos balsa',
  'Porta esferos de chonta',
  'Porta esferos de semilla',
  'Porta retrato',
  'Porta servilleta de balsa',
  'Porta servilletas de pambil',
  'Prevan / Dosio Deidroacetato Anidro gr.',
  'Probetaina Capb / Incronam 30 gr.',
  'Propolen l¡quido juve',
  'propoleo spray',
  'Provola Ahumada 150gr',
  'Provola ahumada bola',
  'Provola Ahumada cilindro kg',
  'Pulsera semilla y plata',
  'Quena ',
  'Quesadillas',
  'Queso fresco',
  'Queso mozzarella 400gr',
  'Queso salinerito andino',
  'Queso salinerito Andino hierbas ',
  'Queso salinerito Cheddar kl',
  'Queso salinerito dambo',
  'Queso salinerito dambo 350gr',
  'Queso Salinerito fresco',
  'Queso salinerito gouda',
  'Queso salinerito gruyere',
  'Queso salinerito gruyere 300gr',
  'Queso salinerito mini al pesto 500gr',
  'Queso salinerito mini andino',
  'Queso salinerito mini andino 250gr',
  'Queso salinerito mini andino aj¡',
  'Queso salinerito mini andino or‚gano',
  'Queso salinerito mini andino or‚gano 250',
  'Queso salinerito mix mini andino ',
  'Queso salinerito mozarella',
  'Queso salinerito mozzarella 250gr',
  'Queso salinerito parmesano 100gr',
  'Queso salinerito Parmesano kl',
  'Queso salinerito sandwich',
  'Queso salinerito sandwich 150gr',
  'Queso salinerito tilsit',
  'Queso salinerito tilsit 250gr',
  'Queso salinerito tilsit or‚gano 300gr',
  'Quinoa Crunch BBQ',
  'Quinoa Crunch vainilla 30gr',
  'Quinoa Crunch vainilla',
  'Quinua 500gr',
  'Quinua org. con cebollin',
  'Quinua org. con hongos',
  'Raid Max',
  'Rasca',
  'Recogedor de Basura',
  'Recogedor de Granos',
  'Reembolso de gastos de acuerdo a factura',
  'Repuesto de Tinta',
  'Reyes magos',
  'Rodapies',
  'Rollo de Cinta Preciadora',
  'Rollo de Etiquetas De Hilo En Papel Couche',
  'Rollo de Hilo De Coser',
  'Rollo de Papel de manos',
  'Rollo de Sobre Envolturas En Papel Bond',
  'Rollo Zuncho Plastico Virgen',
  'Rondador grande',
  'Rondador mini',
  'Rondador peq.',
  'Rosario de semillas',
  'Rosario de semillas (chonta)',
  'Rosario metal',
  'Sacos de Polipropileno / saquillo',
  'SAL HIMALAYA EN GRANO BLESS FUNDA 454G',
  'SAL MARINA SAYWA 150GR (MEDIANO)',
  'SAL MARINA SAYWA 500g + Sal Caja 150g',
  'Salami s',
  'Salero',
  'Sales de ba¤o',
  'Salsa de aj¡ con maracuy ',
  'Salsa de aj¡ con tomate',
  'Salsa de aj¡ dulce con pi¤a',
  'Salsa de aj¡ jalape¤o',
  'Salsa de aj¡ rocoto 100gr',
  'Salsa de aj¡ rocoto amarillo',
  'Salsa de aj¡: tomate/maracuy /ahumado/rocoto rojo-amarillo/ ',
  'Salvado de trigo 200gr',
  'Sangre de drago con certificaci¢n org nica KIWA BCS OKO lt.',
  'Sangre de drago convencional lt.',
  'Sangre de drago convencional',
  'Sangre de drago org nico',
  'Sapak',
  'Sellos autoadhesivos',
  'Semillas de Ca¤ mo. (170 gr).',
  'SEMILLAS DE GIRASOL /CORTEZA 250 gr',
  'SEMILLAS DE GIRASOL PELADA 100 gr',
  'Senta de cabeza',
  'Senta de mano de algod¢n natural',
  'Senta delgada algod¢n natural',
  'Servicio de alquiler',
  'SERVICIO DE PUBLICIDAD',
  'Servicio de transporte (encomienda)',
  'Servicios',
  'Servilleteros tipicos en migaj¢n',
  'Shakap',
  'Shampoo ikiam ungurahua hl 250ml.',
  'Shampoo ikiam ungurahua hl 270ml.',
  'Shampoo ikiam ungurahua HL 30ml.',
  'Shampoo ikiam ungurahua hl gal¢n',
  'Shampoo ikiam ungurahua romero 250ml.',
  'Shampoo ikiam ungurahua romero 270ml.',
  'Shampoo ikiam ungurahua romero gal¢n',
  'Shampoo ungurahua romero l¡quido 60ml.',
  'Sharomix 703',
  'Sharomix 703 plus batch n§ PL0671-0515 gr.',
  'Shigras',
  'Silla ',
  'Solagum Ax gr.',
  'Solitario',
  'Solubilisant Lri gr.',
  'Soluci¢n de norbixina (2.5% p/p)',
  'Sombreros de mujer',
  'Sombreros de semillas',
  'Sombreros de semillas peque¤o',
  'Sorbato De Potasio gr.',
  'Soya en polvo fresa 200gr',
  'Soya en polvo natural 0% az£car 300gr',
  'Soya en polvo natural 200gr',
  'Soya en polvo natural 300gr',
  'Soya en polvo vainilla 200gr',
  'SOYA SALADITA CAMARI 100gr.(FUENTE DE VIDA)',
  'Speck 100gr',
  'SQUIZ 2 LT',
  'Squiz citrus punch',
  'Stevia gotas',
  'Strech Film - Pl stico De Embalaje',
  'S£per 7 (quinua)',
  'Tableta de chocolate ChocoNuse 50 g',
  'Tableta de chocolate Kakauyapa 50 g',
  'Tachau 13 a 17 cm',
  'Tachau hasta 12 cm',
  'Tachau peque¤¡simo',
  'Tamales',
  'Tamborin',
  'Tampu (2 - 4 mts)',
  'Tampu de 20 a 30 cm',
  'Tampu peque¤o de 2 metros',
  'Tapa Blanca (jarabe)',
  'Tapa de Crema fluida dis Top 24/410 Blanco PD.',
  'Tapa de Shampoo Disc Top  24/410 Oro A.',
  'Tapa de Shampoo Flip Top 20 Blanco P / CF.',
  'Tapa sencilla',
  'Tarjeton (3*1)',
  'Tayukunch',
  'Tazas humeadas',
  'Te de Jambi kiwa',
  'Te de salinas',
  'Te Frio ',
  'Temash de kumai',
  'Tesalia ice naranjilla',
  'Texapon N70 / Lauril sulfato de sodio T gr.',
  'Tishimuk (arco con fecha)',
  'Tobilleras',
  'Tocino ahumado 250gr',
  'Tortugas de balsa',
  'Tostada jam¢n o queso',
  'Tostada mixta',
  'Trietanolamina gr.',
  'Tsapa',
  'Tsapas pirograbados',
  'Tsatsa cernidor de tsapa',
  'Tubo de Gel De Aluminio De 30 Gr.',
  'Tunta',
  'Turr¢n crocante Chovis (man¡)',
  'Turr¢n de macadamia',
  'Turron de macadamia 30g',
  'Turron monasterio',
  'Turron salinas',
  'Tutank 15-20 cm',
  'Tutank 21-25 cm',
  'Tutank 26-30 cm',
  'Tutank 31-35 cm',
  'Tutank 41- 45 cm',
  'Tutank normal 36-40 cm',
  'Tutank peque¤¡simo hasta 14cm',
  'Tuwik',
  'Tween 80 / Crillet 4 gr.',
  'Ultrez 21 gr.',
  'U¤a de gato ¬ libra',
  'Unkuship',
  'Uvillas deshidratadas cubiertas con chocolate PACARI',
  'Vainilla silvestre',
  'Vainilla silvestre molida',
  'Varias compras',
  'Vasos de chonta',
  'Velas',
  'Velas de cera de abejas (oso grande)',
  'Velas de cera de abejas (oso peq.)',
  'Velas de panal de abejas',
  'velas ecol¢gicas (paq)',
  'Velas votivos / botones rosas',
  'Vileda de Piso',
  'Vinagre de Manzana ',
  'Vino (consagrar)',
  'Vino de Jamaica',
  'V¡rgen cer mica',
  'Virgen de quito',
  'Virginia Limpia Mueble',
  'Virginia Limpia Vidrio',
  'Vitamina B Complex gr.',
  'Vitamina E Acetato gr.',
  'Wapas (miel) frasco',
  'Wapas miel lt.',
  'Xantan Gum gr.',
  'Yogurt de la Abuela 1000ml (guan bana)',
  'Yogurt de la Abuela 175ml (guan bana)',
  'Yogurt de la Abuela 2000ml',
  'Yogurt de la Abuela 500ml (guan bana)',
  'Yogurt de la Abuela Guan bana 1000ml',
  'Yogurth monasterio 1/4',
  'Yogurth velchi',
  'Yoguth monastrio 2lts',
  'Yuca deshidratada convencional kg.',
  'Yuca deshidratada org nica kg.',
  'Yuca fresca convencional',
  'Yuca fresca org nica',
  'Yuca frita (porci¢n)',
  'ZAIN TEXTO 1EGB PLATAFORMA',
  'ZAIN TEXTO DEL ESTUDIANTE INICIAL',
  'ZAIN TEXTO L SANTO L PEREGRINO 1 BGU',
  'ZAIN TEXTO L SANTO L PEREGRINO 10 EGB',
  'ZAIN TEXTO L SANTO L PEREGRINO 2 BGU',
  'ZAIN TEXTO L SANTO L PEREGRINO 3 BGU',
  'ZAIN TEXTO L SANTO L PEREGRINO 8 EGB',
  'ZAIN TEXTO L SANTO L PEREGRINO 9 EGB',
  'Zapatones normales (pares)',
  ];


  static List<String> getSuggestions(String query) {
    List<String> matches = List();
    matches.addAll(products);
    matches.retainWhere((s) => s.toLowerCase().contains(query.toLowerCase()));
    return matches;
  }
}